import { ScUiArticle } from '../interfaces';

export const ArticleListStub: ScUiArticle[] = [
  {
    title: 'Kress News',
    description: 'Headline',
    url: 'http://google.com',
    date: '',
    photoUrl: 'https://storage.googleapis.com/static-imgs/scope-ui/scope-image-dummy.png',
    mode: 'default',
    publisher: 'Source',
    comment: 'Comment',
  },
  {
    title: 'Kress News',
    description: 'Headline',
    url: 'http://google.com',
    date: '01/27/2019',
    photoUrl: 'https://storage.googleapis.com/static-imgs/scope-ui/scope-image-dummy.png',
    mode: 'edit',
    publisher: 'Source',
    comment: 'Comment',
    linked: true
  },
  {
    title: 'Kress News',
    description: 'Headline',
    url: 'http://google.com',
    date: '01/27/2019',
    photoUrl: 'https://storage.googleapis.com/static-imgs/scope-ui/scope-image-dummy.png',
    mode: 'delete',
    publisher: 'Source',
    comment: 'Comment',
  },
  {
    title: 'Kress News',
    description: 'Headline',
    url: 'http://google.com',
    date: '01/27/2019',
    photoUrl: 'https://storage.googleapis.com/static-imgs/scope-ui/scope-image-dummy.png',
    mode: 'imported',
    publisher: 'Source',
    comment: 'Comment',
  },
  {
    title: 'Kress News',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.' +
      ' Lorem Ipsum has been the industry\'s standard dummy text ever since...',
    url: 'http://google.com',
    date: '01/27/2019',
    photoUrl: '',
    mode: 'default',
    publisher: 'Source',
    comment: 'Comment',
  },
  {
    title: 'Kress News',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.' +
      ' Lorem Ipsum has been the industry\'s standard dummy text ever since...',
    url: 'http://google.com',
    date: '01/27/2019',
    photoUrl: '',
    mode: 'imported',
    publisher: 'Source',
    comment: 'Comment',
  },
  {
    title: 'Kress News',
    description: 'Headline',
    url: 'http://google.com',
    date: '01/27/2019',
    photoUrl: '',
    mode: 'edit',
    publisher: 'Source',
    comment: 'Comment',
  },
];
